### ISSUE TITLE
Updated Libby's personal site

### ISSUE THREAD

**Issue by libbby** [silshack/spring2014#145]
Updated my repository
https://github.com/libbby/spring2014/

**Comment by eah13** [comment]
@libbby This link should be to your site, not your repository.  Take a look at some of these examples if you're not sure about the difference:
https://github.com/silshack/spring2014/issues?milestone=4&page=1&state=closed

**Comment by libbby** [comment]
@eah13 
Whoops,
 here is the correct link:
http://libbby.github.io/spring2014/
