### ISSUE TITLE
Updated Oak's personal site with issues...

### ISSUE THREAD

**Issue by Blucka12** [silshack/spring2014#149]
I'm thinking I got this right...I have issues, nonetheless...

http://blucka12.github.io/spring2014/

**Comment by gerbal** [comment]
@Blucka12 please include a link to your github.io page in this issue

**Comment by eah13** [comment]
@Blucka12 ditto.

**Comment by Blucka12** [comment]
Like that, @gerbal ?

**Comment by gerbal** [comment]
Yep. Though linking to your post is mildly preferred. 
Also include that link in your pull request.
