### ISSUE TITLE
Julie's coding bat exercies

### ISSUE THREAD

**Issue by juliees39** [silshack/spring2014#228]
I've finished my codingbat exercises. You can see them here: http://juliees39.github.io/spring2014/2014/02/06/juliebat.html

**Comment by gerbal** [comment]
@juliees39 good looking post. When you make these issues because you still have a pull request open, be sure to reference that pull request.

#206

**Comment by juliees39** [comment]
@gerbal Hi, yeah I was confused about whether I should open a new pull request. But it looks like my new post just became part of the old pull request. Is that okay?

**Comment by gerbal** [comment]
It's ok if you have an open pull request. Just be sure to reference the open pull request in your issue.
