### ISSUE TITLE
Brittany's Codingbat 2

### ISSUE THREAD

**Issue by eah13** [silshack/spring2014#256]
There was already a pull request open.

**Comment by eah13** [comment]
Actually- this shoudl keep track of the extra credit, not codingbat.  Sorry!  WIll close once I've looked it over.

**Comment by eah13** [comment]
@britth I don't believe we ever got to go over your extra credit answers in class.  Let me know if you'd like to do so!

**Comment by britth** [comment]
@eah13 nah, we don't have to; thanks!
